Repository 2025-LIKELION-BuyDobong/2025-LIKELION-BuyDobong-FE, pull requests merged in 2025-09, with the labels that each got.

#34 [Feat] 모달 공통컴포넌트 구현
  src/components/Modal.tsx
  src/routes/customer/CustomerHome.tsx
  src/routes/merchant/MerchantHome.tsx
  src/styles/ModalStyle.ts
  src/styles/merchant/MerchantHomeStyle.ts
Labels: ✨ Feat, ♻️ Refactor

#36 [Feat] 상점 대표사진 삭제 구현
  src/assets/BlurClose.svg
  src/routes/merchant/StoreRegister.tsx
  src/styles/merchant/StoreRegisterStyle.ts
Labels: ✨ Feat, ♻️ Refactor

#46 [Refactor] 리팩토링 QA 1차 대응 - UI 디테일 수정
  index.html
  public/_redirects
  src/components/FloatingButtons.tsx
  src/components/Header.tsx
  src/components/customer/NearbyStores.tsx
  src/routes/SignupRole.tsx
  src/routes/customer/KeywordSearch.tsx
  src/styles/HeaderStyle.ts
  src/styles/LoginStyle.ts
  src/styles/ModalStyle.ts
  src/styles/SignupRoleStyle.tsx
  src/styles/SignupStyle.ts
  src/styles/customer/KeywordSearchStyle.ts
  src/styles/customer/MarketDetailStyle.ts
  src/styles/customer/MarketSearchStyle.ts
  src/styles/customer/ProductSearchStyle.ts
  vercel.json
Labels: 🐛 Fix, ♻️ Refactor

#48 [Fix] 2차 QA 반영
  index.html
  src/components/FloatingButtons.tsx
  src/components/customer/InterestNudge.tsx
  src/components/customer/NearbyStores.tsx
  src/components/customer/PopularKeywords.tsx
  src/lib/api/stores.ts
  src/routes/customer/CustomerHome.tsx
  src/routes/customer/MarketDetail.tsx
  src/routes/merchant/MerchantHome.tsx
  src/styles/GlobalStyle.ts
  src/styles/HeaderStyle.ts
  src/styles/LoginHomeStyle.ts
  src/styles/LoginStyle.ts
  src/styles/ModalStyle.ts
  src/styles/SignupStyle.ts
  src/styles/customer/InterestMarketStyle.ts
  src/styles/customer/MarketDetailStyle.ts
  src/styles/merchant/MerchantHomeStyle.ts
  src/styles/merchant/ProductCreateStyle.ts
  src/styles/merchant/ProductRegisterStyle.ts
  src/styles/merchant/SpecialRegisterStyle.ts
  src/styles/merchant/StoreRegisterStyle.ts
Labels: 🐛 Fix

#49 [Fix] 관심 키워드 플로팅 위치 수정
  src/components/customer/InterestNudge.tsx
Labels: 🐛 Fix
